import { useEffect,useMemo,useState } from "react";import { createRoot } from "react-dom/client";import { copyToClipboard } from "neutron-tools/app";import { createOrder,finalizeOrder,listMenus,loadConfig,loadOrder,saveConfig,type Config,type Menu,type Order } from "./api.ts";import "./style.scss";
const processing=new Set(["capture_in_progress","cancel_in_progress","topup_in_progress","paid_pending_topup"]);
function App(){const[config,setConfig]=useState<Config|null>(null);const[menus,setMenus]=useState<Menu[]>([]);const[menuId,setMenuId]=useState("");const[order,setOrder]=useState<Order|null>(null);const[service,setService]=useState("");const[hosted,setHosted]=useState("");const[handoff,setHandoff]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const selected=useMemo(()=>menus.find(menu=>menu.id===menuId),[menus,menuId]);
useEffect(()=>{void boot()},[]);useEffect(()=>{if(!order||!processing.has(order.status))return;const timer=setInterval(()=>void refreshOrder(order.orderId),4000);return()=>clearInterval(timer)},[order?.orderId,order?.status]);
async function boot(){await run(async()=>{const next=await loadConfig();setConfig(next);setService(next.serviceCanister);setHosted(next.hostedCheckoutUrl);if(next.configured&&next.backendReserved){const values=await listMenus();setMenus(values);setMenuId(values[0]?.id??"");if(next.lastOrderId)try{setOrder(await loadOrder(next.lastOrderId))}catch{/* recover from service state in UI */}}})}
async function configure(){await run(async()=>{const next=await saveConfig(service.trim(),hosted.trim().replace(/\/$/,""));setConfig(next);const values=await listMenus();setMenus(values);setMenuId(values[0]?.id??"")})}
async function buy(){if(!config||!selected)return;await run(async()=>{const created=await createOrder(selected.id,crypto.randomUUID());setOrder(created);const url=`${config.hostedCheckoutUrl}/neutron-checkout.html#client_secret=${encodeURIComponent(created.clientSecret)}&order_id=${encodeURIComponent(created.orderId)}`;setHandoff(url);setMessage("Order created. Copy the private handoff URL, finish card verification in a new browser tab, then return to finalize.")})}
async function finalize(){if(!order)return;await run(async()=>{const next=await finalizeOrder(order.orderId);setOrder(next);setHandoff("");setMessage(statusText(next.status))})}
async function refreshOrder(id:string){try{const next=await loadOrder(id);setOrder(next);if(next.status==="topup_succeeded")setMessage(statusText(next.status))}catch(reason){setMessage(errorText(reason))}}
async function copy(){if(!handoff)return;await copyToClipboard(handoff);setMessage("Private handoff URL copied. Its fragment is not sent to the Worker server.")}
async function run(action:()=>Promise<void>){setBusy(true);setMessage("");try{await action()}catch(reason){setMessage(errorText(reason))}finally{setBusy(false)}}
return <main className="cycles-app"><header><p>EXECUTION FUEL / THIS NEUTRON</p><h1>Keep your cloud<br/><em>awake.</em></h1><div className="target"><span>TARGET CANISTER</span><code>{config?.neutronCanister||"loading…"}</code></div></header>{!config?.configured||!config.backendReserved?<section className="setup"><span>SERVICE BINDING</span><h2>Connect the confidential checkout service</h2><label>Service canister<input value={service} onChange={e=>setService(e.target.value)} placeholder="aaaaa-aa"/></label><label>Hosted checkout origin<input value={hosted} onChange={e=>setHosted(e.target.value)} placeholder="https://checkout.example"/></label><button disabled={busy||!service.trim()||!hosted.trim()} onClick={()=>void configure()}>Save exact binding</button>{config?.configured&&!config.backendReserved&&<p>Reserve all four exact backend methods in Neutron Settings, then save again.</p>}</section>:<><section className="menus">{menus.map(menu=><button key={menu.id} className={menu.id===menuId?"selected":""} onClick={()=>setMenuId(menu.id)}><span>{menu.label}</span><strong>${(Number(menu.grossUsdCents)/100).toFixed(2)}</strong><code>price v{menu.priceVersion}</code></button>)}</section><section className="checkout"><div><span>ORDER</span><h2>{order?statusText(order.status):"Ready to create"}</h2><p>{order?`${formatCycles(order.cyclesAmount)} → ${order.targetCanister}`:"Target is fixed to the calling Neutron canister."}</p></div>{!order||["payment_failed","payment_canceled","expired","topup_succeeded"].includes(order.status)?<button disabled={busy||!selected} onClick={()=>void buy()}>Buy {selected?`$${(Number(selected.grossUsdCents)/100).toFixed(2)}`:"cycles"}</button>:<button disabled={busy} onClick={()=>void finalize()}>Finalize & top up</button>}</section>{handoff&&<section className="handoff"><span>HOSTED CARD HANDOFF</span><p>Neutron's CSP blocks Stripe.js by design. Card and 3DS UI run only in the hosted checkout page.</p><button onClick={()=>void copy()}>Copy private checkout URL</button><small>Client secret stays in the URL fragment and is cleared from this Tile after finalization.</small></section>}</>}{message&&<output>{message}</output>}<footer>Never auto-retries an outcome-unknown cycles deposit.</footer></main>}
function formatCycles(value:string){const amount=Number(value)/1e12;return Number.isFinite(amount)?`${amount.toLocaleString(undefined,{maximumFractionDigits:3})} T cycles`:`${value} cycles`}function statusText(status:string){return({created:"Card confirmation required",capture_in_progress:"Capturing payment",cancel_in_progress:"Canceling authorization",paid_pending_topup:"Paid — operator recovery",topup_in_progress:"Top-up outcome pending",topup_succeeded:"Cycles added",payment_failed:"Payment failed",payment_canceled:"Payment canceled",expired:"Order expired"}as Record<string,string>)[status]??status}function errorText(reason:unknown){return reason instanceof Error?reason.message:String(reason)}const root=document.getElementById("root");if(!root)throw new Error("Root element not found");createRoot(root).render(<App/>);
