import { isJsonObject, querySelf, updateSelf, type JsonObject, type JsonValue } from "neutron-tools/app";
export type Config = { configured: boolean; serviceCanister: string; hostedCheckoutUrl: string; neutronCanister: string; lastOrderId: string; lastOrderStatus: string; lastCyclesAmount: string; lastGrossUsdCents: string; lastError: string; backendReserved: boolean; revision: string };
export type Menu = { id: string; label: string; grossUsdCents: string; netUsdCents: string; enabled: boolean; priceVersion: string };
export type Order = { orderId: string; clientSecret: string; status: string; targetCanister: string; cyclesAmount: string; grossUsdCents: string; lastError: string };
export async function loadConfig(): Promise<Config> { return parseConfig(await querySelf("cycles_checkout_config")); }
export async function saveConfig(serviceCanister:string,hostedCheckoutUrl:string):Promise<Config>{return parseConfig(await updateSelf("cycles_checkout_config_save",[serviceCanister,hostedCheckoutUrl]))}
export async function listMenus():Promise<Menu[]>{const row=object(await updateSelf("cycles_price_menus"),"price menus");if(row.ok!==true)throw new Error(text(row.error));if(!Array.isArray(row.menus))throw new Error("Invalid price menus");return row.menus.map(value=>{const menu=object(value,"price menu");return{id:text(menu.id),label:text(menu.menu_label),grossUsdCents:nat(menu.gross_usd_cents),netUsdCents:nat(menu.net_usd_cents),enabled:bool(menu.enabled),priceVersion:nat(menu.price_version)}})}
export async function createOrder(priceMenuId:string,clientRequestId:string):Promise<Order>{return order(await updateSelf("cycles_create_order",[priceMenuId,clientRequestId]))}
export async function loadOrder(orderId:string):Promise<Order>{return order(await updateSelf("cycles_order_status",[orderId]))}
export async function finalizeOrder(orderId:string):Promise<Order>{return order(await updateSelf("cycles_finalize_order",[orderId]))}
function order(value:JsonValue):Order{const row=object(value,"cycles order");if(row.ok!==true)throw new Error(text(row.error));return{orderId:text(row.order_id),clientSecret:text(row.client_secret),status:text(row.status),targetCanister:text(row.target_canister),cyclesAmount:text(row.cycles_amount),grossUsdCents:nat(row.gross_usd_cents),lastError:text(row.last_error)}}
function parseConfig(value:JsonValue):Config{const row=object(value,"cycles config");return{configured:bool(row.configured),serviceCanister:text(row.service_canister),hostedCheckoutUrl:text(row.hosted_checkout_url),neutronCanister:text(row.neutron_canister),lastOrderId:text(row.last_order_id),lastOrderStatus:text(row.last_order_status),lastCyclesAmount:text(row.last_cycles_amount),lastGrossUsdCents:nat(row.last_gross_usd_cents),lastError:text(row.last_error),backendReserved:bool(row.backend_reserved),revision:nat(row.revision)}}
function object(value:unknown,label:string):JsonObject{if(!isJsonObject(value))throw new Error(`Invalid ${label}`);return value as JsonObject}function text(value:unknown):string{if(typeof value!=="string")throw new Error("Invalid text response");return value}function bool(value:unknown):boolean{if(typeof value!=="boolean")throw new Error("Invalid boolean response");return value}function nat(value:unknown):string{const result=text(value);if(!/^(0|[1-9][0-9]*)$/.test(result))throw new Error("Invalid natural response");return result}
