import { useState, type FormEvent } from "react";
import type { Section, TrustConsoleActions, TrustConsoleModel } from "./model.ts";

const sections: Array<{ id: Section; label: string; mark: string }> = [{ id: "overview", label: "Overview", mark: "01" }, { id: "github", label: "GitHub", mark: "02" }, { id: "tasks", label: "Tasks", mark: "03" }, { id: "cyclemint", label: "CycleMint", mark: "04" }];

export function TrustConsoleView({ model, section, actions, busy = false, error }: { model: TrustConsoleModel; section: Section; actions: TrustConsoleActions; busy?: boolean; error?: string }) {
  return <main className="console-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">TC</span><div><strong>TRUST CONSOLE</strong><small>USER-OWNED CONTROL PLANE</small></div></div><nav aria-label="Console sections">{sections.map((item) => <button key={item.id} className={section === item.id ? "active" : ""} onClick={() => actions.navigate(item.id)}><span>{item.mark}</span>{item.label}</button>)}</nav><div className="side-proof"><i></i><b>0 secrets exposed</b><small>Consumers borrow operations, never credentials.</small></div></aside>
    <div className="workspace"><header className="topbar"><div><span className="live-dot"></span>OWNER BOUNDARY ACTIVE</div><div className="top-metrics"><span>3 capability groups</span><span>1 resident service</span><b>{model.demo ? "DEMO EVIDENCE" : "LIVE STATE"}</b></div></header>
      {model.demo && <div className="demo-banner">Illustrative demo data · no credentials</div>}{error && <div className="alert">{error}</div>}
      {section === "overview" && <Overview model={model}/>}
      {section === "github" && <GitHubPanel model={model} actions={actions} busy={busy}/>}
      {section === "tasks" && <TasksPanel model={model} actions={actions} busy={busy}/>}
      {section === "cyclemint" && <CyclesPanel model={model} actions={actions} busy={busy}/>}
    </div>
  </main>;
}

function Overview({ model }: { model: TrustConsoleModel }) {
  const open = model.tasks.filter((task) => task.status === "open").length; const succeeded = model.jobs.filter((job) => job.status === "succeeded").length;
  return <section className="page overview"><div className="hero"><p className="eyebrow">SOVEREIGN CAPABILITY ROUTING</p><h1>Lend the operation.<br/><em>Keep the authority.</em></h1><p className="lede">Bring your own GitHub token, connect an owner-approved CycleMint service, and lend only narrow operations.</p></div>
    <div className="rail" aria-label="Capability flow"><Flow label="Consumer" detail="agent_runner" tone="cyan"/><Arrow/><Flow label="Policy boundary" detail="repo + operation" tone="mint"/><Arrow/><Flow label="Capability" detail="durable execution" tone="amber"/><Arrow/><Flow label="Outcome" detail="redacted evidence" tone="coral"/></div>
    <div className="cap-grid"><Capability title="GitHub" kicker="SCOPED DRIVER" status={model.connection.connected ? "CONNECTED" : "DEMO READY"} value={`${model.policies.length} policies`} tone="mint"/><Capability title="Tasks" kicker="DURABLE WORK" status="READY" value={`${open} open`} tone="cyan"/><Capability title="CycleMint" kicker="EXECUTION FUEL" status={model.cycles.configured ? "CONFIGURED" : "SETUP"} value={model.cycles.lastOrderStatus || "No top-up yet"} tone="amber"/></div>
    <div className="proof-grid"><article><span>SUCCESSFUL JOBS</span><strong>{succeeded.toString().padStart(2,"0")}</strong><small>Durable, reconciled external writes</small></article><article><span>OPEN WORK</span><strong>{open.toString().padStart(2,"0")}</strong><small>Revision-safe owner tasks</small></article><article><span>SECRETS RETURNED</span><strong>00</strong><small>Across every public summary</small></article></div>
  </section>;
}
function Flow({label,detail,tone}:{label:string;detail:string;tone:string}){return <div className={`flow ${tone}`}><i></i><small>{label}</small><b>{detail}</b></div>} function Arrow(){return <span className="arrow">→</span>}
function Capability({title,kicker,status,value,tone}:{title:string;kicker:string;status:string;value:string;tone:string}){return <article className={`cap-card ${tone}`}><div><span>{kicker}</span><b>{status}</b></div><h2>{title}</h2><p>{value}</p><footer><i></i>OWNER MEDIATED</footer></article>}

function GitHubPanel({model,actions,busy=false}:{model:TrustConsoleModel;actions:TrustConsoleActions;busy?:boolean}){const [token,setToken]=useState("");const simulation=model.jobs.filter(job=>job.consumerAppId==="judge_demo"&&job.owner==="neutron-demo").at(-1);return <section className="page"><PageHead index="02" title="GitHub Driver" copy="Try the durable control path without a credential, then connect GitHub when ready."/><article className="demo-runner"><div className="demo-intro"><span>SAFE SIMULATION</span><h2>Watch authority become evidence.</h2><p>Runs the real policy, durable Job, lease and reconciliation path. It never contacts GitHub.</p><button disabled={busy} onClick={()=>void actions.runGitHubDemo()}>{busy?"Running durable workflow…":"Run GitHub workflow demo"}</button></div><div className="demo-steps" aria-live="polite"><DemoStep label="Policy" value={simulation?"granted":"deny by default"} active={Boolean(simulation)}/><DemoStep label="Durable job" value={simulation?simulation.jobUid.slice(0,8):"not started"} active={Boolean(simulation)}/><DemoStep label="Outcome" value={simulation?simulation.status.replaceAll("_"," "):"awaiting run"} active={simulation?.status==="succeeded"}/></div><footer>SIMULATION · NO CREDENTIAL · NO GITHUB WRITE</footer></article><div className="two-col"><article className="panel"><PanelHead title="Connection vault" tag={model.connection.connected?"CONNECTED":"OPTIONAL FOR DEMO"}/><SetupOwnership tone="mint" label="YOU PROVIDE" title="Your GitHub personal access token">Create it in your GitHub account and paste it here. Trust Console keeps it in this Neutron's SEV-protected canister state; consumer apps receive only the repository operations you approve.</SetupOwnership>{model.connection.connected?<div className="connection"><strong>{model.connection.label||"GitHub"}</strong><code>•••• {model.connection.tokenSuffix}</code><p>The credential is never returned to consumer apps.</p></div>:<form onSubmit={async(e)=>{e.preventDefault();await actions.connectGitHub(token,"Owner GitHub")}}><label>Your personal access token<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="github_pat_••••" minLength={20}/></label><small className="field-help">Use the narrowest repository and issue permissions needed for the operations you plan to grant.</small><button disabled={busy||token.length<20}>Save my token for real GitHub writes</button></form>}</article><article className="panel"><PanelHead title="Repository policy" tag="DENY BY DEFAULT"/><PolicyForm actions={actions} busy={busy}/></article></div><article className="panel table-panel"><PanelHead title="Durable job ledger" tag={`${model.jobs.length} JOBS`}/><JobTable jobs={model.jobs}/></article></section>}
function DemoStep({label,value,active}:{label:string;value:string;active:boolean}){return <div className={active?"active":""}><i></i><span>{label}</span><b>{value}</b></div>}
function PolicyForm({actions,busy=false}:{actions:TrustConsoleActions;busy?:boolean}){const [consumer,setConsumer]=useState("agent_runner"),[repo,setRepo]=useState("acme/launchpad");return <form className="inline-form" onSubmit={async(e)=>{e.preventDefault();const [owner,name]=repo.split("/");if(owner&&name)await actions.saveGitHubPolicy(consumer,owner,name)}}><label>Consumer<input value={consumer} onChange={e=>setConsumer(e.target.value)}/></label><label>Repository<input value={repo} onChange={e=>setRepo(e.target.value)}/></label><button disabled={busy}>Grant issue read + create</button></form>}
function JobTable({jobs}:{jobs:TrustConsoleModel["jobs"]}){return <div className="data-table"><div className="table-row head"><span>JOB</span><span>CONSUMER</span><span>REPOSITORY</span><span>STATE</span><span>OUTCOME</span></div>{jobs.length?jobs.slice().reverse().slice(0,6).map(job=><div className="table-row" key={job.id}><code>{job.jobUid.slice(0,8)}</code><span>{job.consumerAppId}</span><span>{job.owner}/{job.repo}</span><b className={`state ${job.status}`}>{job.status.replaceAll("_"," ")}</b><span>{job.resultSummary||"Awaiting executor"}</span></div>):<Empty text="No durable jobs yet."/>}</div>}

function TasksPanel({model,actions,busy=false}:{model:TrustConsoleModel;actions:TrustConsoleActions;busy?:boolean}){const [title,setTitle]=useState("");return <section className="page"><PageHead index="03" title="Durable Tasks" copy="Turn capabilities into revision-safe work with traceable origins."/><article className="panel"><form className="task-compose" onSubmit={async(e)=>{e.preventDefault();await actions.createTask(title);setTitle("")}}><label>New owner task<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Describe the next durable outcome"/></label><button disabled={busy||!title.trim()}>Create task</button></form></article><div className="task-list">{model.tasks.length?model.tasks.map(task=><article key={task.id} className={task.status}><div><span>{task.sourceKind==="github_issue"?"GITHUB ISSUE":"MANUAL"}</span><h3>{task.title}</h3><p>{task.sourceKind==="github_issue"?`${task.sourceOwner}/${task.sourceRepo} #${task.sourceIssueNumber}`:`Revision ${task.revision}`}</p></div><button disabled={busy||task.status==="completed"} onClick={()=>void actions.completeTask(task.id,task.revision)}>{task.status==="completed"?"Completed":"Mark complete"}</button></article>):<Empty text="No tasks yet. The control plane is ready."/>}</div></section>}

function CyclesPanel({model,actions,busy=false}:{model:TrustConsoleModel;actions:TrustConsoleActions;busy?:boolean}){const [service,setService]=useState(model.cycles.serviceCanister),[url,setUrl]=useState(model.cycles.hostedCheckoutUrl);return <section className="page"><PageHead index="04" title="CycleMint" copy="Purchase and top up existing cycles through an owner-approved Stripe service."/><div className="notice"><b>TOP-UP, NOT TOKEN ISSUANCE</b><span>CycleMint adds execution fuel to this Neutron. It does not create a new cycles asset.</span></div><div className="two-col"><article className="panel"><PanelHead title="Service boundary" tag={model.cycles.backendReserved?"EXACT ACCESS RESERVED":"SETUP REQUIRED"}/><SetupOwnership tone="amber" label="NO STRIPE KEY HERE" title="Connect an approved CycleMint endpoint">Enter its service canister and hosted checkout URL. Stripe secrets stay with the external CycleMint service operator; payment opens in that service's hosted checkout.</SetupOwnership><form onSubmit={async(e)=>{e.preventDefault();await actions.configureCycleMint(service,url)}}><label>Service canister<input value={service} onChange={e=>setService(e.target.value)} placeholder="aaaaa-aa"/></label><label>Hosted checkout URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://checkout.example"/></label><button disabled={busy||!service||!url}>Save owner-approved service</button></form></article><article className="panel"><PanelHead title="Top-up menu" tag={`${model.menus.length} OPTIONS`}/>{model.menus.length?model.menus.map(menu=><button className="price" key={menu.id} onClick={()=>void actions.createCycleOrder(menu.id)} disabled={busy}><span>{menu.label}</span><b>${(Number(menu.grossUsdCents)/100).toFixed(2)}</b></button>):<button onClick={()=>void actions.refreshMenus()} disabled={busy||!model.cycles.configured}>Load price menu</button>}</article></div>{(model.order||model.cycles.lastOrderStatus)&&<article className="order-evidence"><span>LAST TOP-UP</span><b>{model.order?.status||model.cycles.lastOrderStatus}</b><strong>{model.order?.cyclesAmount||model.cycles.lastCyclesAmount} cycles</strong><small>Target {model.order?.targetCanister||model.cycles.neutronCanister}</small></article>}</section>}

function SetupOwnership({tone,label,title,children}:{tone:"mint"|"amber";label:string;title:string;children:string}){return <div className={`setup-ownership ${tone}`}><span>{label}</span><strong>{title}</strong><p>{children}</p></div>}

function PageHead({index,title,copy}:{index:string;title:string;copy:string}){return <header className="page-head"><span>{index}</span><div><h1>{title}</h1><p>{copy}</p></div></header>} function PanelHead({title,tag}:{title:string;tag:string}){return <div className="panel-head"><h2>{title}</h2><span>{tag}</span></div>} function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
